title:            虛
tagline:          為夢留下為時間.
description:      最最親愛的局部,最最重要的現在.
#Comment out url when working locally to resolve base urls correctly
url: http://poemcao.github.io/cn

# Owner/author information
owner:
  name:           shi | 詩
  avatar:         avatar.png
  bio:            "Aesthete & Athlete"
  email:          poemcao@gmail.com
  twitter:        poemcao        
  github:         poemcao              
  disqus:         poemcao
  # Plug in your disqus shortname!
  

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Github
    url: https://github.io/poemcao
    external: true
  - title: 詩 ?
    url: http://poemcao.github.io
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Chungking
future:      true
pygments:    true
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]